# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetGlTransactionsMethodParams(BaseModel):
    """
    GetGlTransactionsMethodParams
    """ # noqa: E501
    property_ids: StrictStr = Field(description="This is a required field. This field accepts comma seperated multiple values.", alias="propertyIds")
    gl_account_from: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value.", alias="glAccountFrom")
    gl_account_to: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value.", alias="glAccountTo")
    post_month_from: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value. If no post month is provided, then the default post month of the prope rty will be used. If multiple properties are passed then the post mon th of any property would be used randomly.", alias="postMonthFrom")
    post_month_to: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value.", alias="postMonthTo")
    post_date_from: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value.", alias="postDateFrom")
    post_date_to: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value.", alias="postDateTo")
    is_cash_book: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value.", alias="isCashBook")
    is_detailed: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value.", alias="isDetailed")
    gl_tree_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value.", alias="glTreeId")
    gl_book_type_ids: Optional[StrictInt] = Field(default=None, description="  This is an optional field. This field accepts comma seperated multiple values.", alias="glBookTypeIds")
    transaction_date_from: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value. This is the actual system created date of the transaction.", alias="transactionDateFrom")
    transaction_date_to: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value. This is the actual system created date of the transaction.", alias="transactionDateTo")
    exclude_ap_transactions: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This flag will filter off any ap transactions from the response.", alias="excludeApTransactions")
    exclude_ar_transactions: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This flag will filter off any Ar Transactions from the response.", alias="excludeArTransactions")
    exclude_exported_transactions: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. If passed as true (1) the API will not return any transaction that was previously marked exported using the markGlTransactionsExported API. Transaction exported under a different export format in Entrata wil l still qualify to be returned until specifically marked exported over the markGlTransactionsExported API.", alias="excludeExportedTransactions")
    __properties: ClassVar[List[str]] = ["propertyIds", "glAccountFrom", "glAccountTo", "postMonthFrom", "postMonthTo", "postDateFrom", "postDateTo", "isCashBook", "isDetailed", "glTreeId", "glBookTypeIds", "transactionDateFrom", "transactionDateTo", "excludeApTransactions", "excludeArTransactions", "excludeExportedTransactions"]

    @field_validator('is_cash_book')
    def is_cash_book_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    @field_validator('is_detailed')
    def is_detailed_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    @field_validator('exclude_ap_transactions')
    def exclude_ap_transactions_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    @field_validator('exclude_ar_transactions')
    def exclude_ar_transactions_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    @field_validator('exclude_exported_transactions')
    def exclude_exported_transactions_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGlTransactionsMethodParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGlTransactionsMethodParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "propertyIds": obj.get("propertyIds"),
            "glAccountFrom": obj.get("glAccountFrom"),
            "glAccountTo": obj.get("glAccountTo"),
            "postMonthFrom": obj.get("postMonthFrom"),
            "postMonthTo": obj.get("postMonthTo"),
            "postDateFrom": obj.get("postDateFrom"),
            "postDateTo": obj.get("postDateTo"),
            "isCashBook": obj.get("isCashBook"),
            "isDetailed": obj.get("isDetailed"),
            "glTreeId": obj.get("glTreeId"),
            "glBookTypeIds": obj.get("glBookTypeIds"),
            "transactionDateFrom": obj.get("transactionDateFrom"),
            "transactionDateTo": obj.get("transactionDateTo"),
            "excludeApTransactions": obj.get("excludeApTransactions"),
            "excludeArTransactions": obj.get("excludeArTransactions"),
            "excludeExportedTransactions": obj.get("excludeExportedTransactions")
        })
        return _obj


