# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from entrata_api_client.models.get_ar_invoices import GetArInvoices
from entrata_api_client.models.get_lease_ar_transactions import GetLeaseArTransactions
from entrata_api_client.models.get_mits_lease_ar_transactions import GetMitsLeaseArTransactions
from entrata_api_client.models.send_lease_ar_transaction_reversals import SendLeaseArTransactionReversals
from entrata_api_client.models.send_lease_ar_transactions import SendLeaseArTransactions
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ORGSV1ARTRANSACTIONSPOSTREQUESTINNER_ONE_OF_SCHEMAS = ["GetArInvoices", "GetLeaseArTransactions", "GetMitsLeaseArTransactions", "SendLeaseArTransactionReversals", "SendLeaseArTransactions"]

class OrgsV1ArtransactionsPostRequestInner(BaseModel):
    """
    OrgsV1ArtransactionsPostRequestInner
    """
    # data type: GetArInvoices
    oneof_schema_1_validator: Optional[GetArInvoices] = None
    # data type: GetLeaseArTransactions
    oneof_schema_2_validator: Optional[GetLeaseArTransactions] = None
    # data type: GetMitsLeaseArTransactions
    oneof_schema_3_validator: Optional[GetMitsLeaseArTransactions] = None
    # data type: SendLeaseArTransactionReversals
    oneof_schema_4_validator: Optional[SendLeaseArTransactionReversals] = None
    # data type: SendLeaseArTransactions
    oneof_schema_5_validator: Optional[SendLeaseArTransactions] = None
    actual_instance: Optional[Union[GetArInvoices, GetLeaseArTransactions, GetMitsLeaseArTransactions, SendLeaseArTransactionReversals, SendLeaseArTransactions]] = None
    one_of_schemas: Set[str] = { "GetArInvoices", "GetLeaseArTransactions", "GetMitsLeaseArTransactions", "SendLeaseArTransactionReversals", "SendLeaseArTransactions" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = OrgsV1ArtransactionsPostRequestInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: GetArInvoices
        if not isinstance(v, GetArInvoices):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetArInvoices`")
        else:
            match += 1
        # validate data type: GetLeaseArTransactions
        if not isinstance(v, GetLeaseArTransactions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetLeaseArTransactions`")
        else:
            match += 1
        # validate data type: GetMitsLeaseArTransactions
        if not isinstance(v, GetMitsLeaseArTransactions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetMitsLeaseArTransactions`")
        else:
            match += 1
        # validate data type: SendLeaseArTransactionReversals
        if not isinstance(v, SendLeaseArTransactionReversals):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SendLeaseArTransactionReversals`")
        else:
            match += 1
        # validate data type: SendLeaseArTransactions
        if not isinstance(v, SendLeaseArTransactions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SendLeaseArTransactions`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in OrgsV1ArtransactionsPostRequestInner with oneOf schemas: GetArInvoices, GetLeaseArTransactions, GetMitsLeaseArTransactions, SendLeaseArTransactionReversals, SendLeaseArTransactions. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in OrgsV1ArtransactionsPostRequestInner with oneOf schemas: GetArInvoices, GetLeaseArTransactions, GetMitsLeaseArTransactions, SendLeaseArTransactionReversals, SendLeaseArTransactions. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into GetArInvoices
        try:
            instance.actual_instance = GetArInvoices.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GetLeaseArTransactions
        try:
            instance.actual_instance = GetLeaseArTransactions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GetMitsLeaseArTransactions
        try:
            instance.actual_instance = GetMitsLeaseArTransactions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SendLeaseArTransactionReversals
        try:
            instance.actual_instance = SendLeaseArTransactionReversals.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SendLeaseArTransactions
        try:
            instance.actual_instance = SendLeaseArTransactions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into OrgsV1ArtransactionsPostRequestInner with oneOf schemas: GetArInvoices, GetLeaseArTransactions, GetMitsLeaseArTransactions, SendLeaseArTransactionReversals, SendLeaseArTransactions. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into OrgsV1ArtransactionsPostRequestInner with oneOf schemas: GetArInvoices, GetLeaseArTransactions, GetMitsLeaseArTransactions, SendLeaseArTransactionReversals, SendLeaseArTransactions. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GetArInvoices, GetLeaseArTransactions, GetMitsLeaseArTransactions, SendLeaseArTransactionReversals, SendLeaseArTransactions]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


