# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.get_ar_invoices_success_response import GetArInvoicesSuccessResponse
from openapi_client.models.get_lease_ar_transactions_success_response import GetLeaseArTransactionsSuccessResponse
from openapi_client.models.get_mits_lease_ar_transactions_success_response import GetMitsLeaseArTransactionsSuccessResponse
from openapi_client.models.send_lease_ar_transaction_reversals_success_response import SendLeaseArTransactionReversalsSuccessResponse
from openapi_client.models.send_lease_ar_transactions_success_response import SendLeaseArTransactionsSuccessResponse
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ORGSV1ARTRANSACTIONSPOST200RESPONSE_ONE_OF_SCHEMAS = ["GetArInvoicesSuccessResponse", "GetLeaseArTransactionsSuccessResponse", "GetMitsLeaseArTransactionsSuccessResponse", "SendLeaseArTransactionReversalsSuccessResponse", "SendLeaseArTransactionsSuccessResponse"]

class OrgsV1ArtransactionsPost200Response(BaseModel):
    """
    OrgsV1ArtransactionsPost200Response
    """
    # data type: GetArInvoicesSuccessResponse
    oneof_schema_1_validator: Optional[GetArInvoicesSuccessResponse] = None
    # data type: GetLeaseArTransactionsSuccessResponse
    oneof_schema_2_validator: Optional[GetLeaseArTransactionsSuccessResponse] = None
    # data type: GetMitsLeaseArTransactionsSuccessResponse
    oneof_schema_3_validator: Optional[GetMitsLeaseArTransactionsSuccessResponse] = None
    # data type: SendLeaseArTransactionReversalsSuccessResponse
    oneof_schema_4_validator: Optional[SendLeaseArTransactionReversalsSuccessResponse] = None
    # data type: SendLeaseArTransactionsSuccessResponse
    oneof_schema_5_validator: Optional[SendLeaseArTransactionsSuccessResponse] = None
    actual_instance: Optional[Union[GetArInvoicesSuccessResponse, GetLeaseArTransactionsSuccessResponse, GetMitsLeaseArTransactionsSuccessResponse, SendLeaseArTransactionReversalsSuccessResponse, SendLeaseArTransactionsSuccessResponse]] = None
    one_of_schemas: Set[str] = { "GetArInvoicesSuccessResponse", "GetLeaseArTransactionsSuccessResponse", "GetMitsLeaseArTransactionsSuccessResponse", "SendLeaseArTransactionReversalsSuccessResponse", "SendLeaseArTransactionsSuccessResponse" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = OrgsV1ArtransactionsPost200Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: GetArInvoicesSuccessResponse
        if not isinstance(v, GetArInvoicesSuccessResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetArInvoicesSuccessResponse`")
        else:
            match += 1
        # validate data type: GetLeaseArTransactionsSuccessResponse
        if not isinstance(v, GetLeaseArTransactionsSuccessResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetLeaseArTransactionsSuccessResponse`")
        else:
            match += 1
        # validate data type: GetMitsLeaseArTransactionsSuccessResponse
        if not isinstance(v, GetMitsLeaseArTransactionsSuccessResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetMitsLeaseArTransactionsSuccessResponse`")
        else:
            match += 1
        # validate data type: SendLeaseArTransactionReversalsSuccessResponse
        if not isinstance(v, SendLeaseArTransactionReversalsSuccessResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SendLeaseArTransactionReversalsSuccessResponse`")
        else:
            match += 1
        # validate data type: SendLeaseArTransactionsSuccessResponse
        if not isinstance(v, SendLeaseArTransactionsSuccessResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SendLeaseArTransactionsSuccessResponse`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in OrgsV1ArtransactionsPost200Response with oneOf schemas: GetArInvoicesSuccessResponse, GetLeaseArTransactionsSuccessResponse, GetMitsLeaseArTransactionsSuccessResponse, SendLeaseArTransactionReversalsSuccessResponse, SendLeaseArTransactionsSuccessResponse. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in OrgsV1ArtransactionsPost200Response with oneOf schemas: GetArInvoicesSuccessResponse, GetLeaseArTransactionsSuccessResponse, GetMitsLeaseArTransactionsSuccessResponse, SendLeaseArTransactionReversalsSuccessResponse, SendLeaseArTransactionsSuccessResponse. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into GetArInvoicesSuccessResponse
        try:
            instance.actual_instance = GetArInvoicesSuccessResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GetLeaseArTransactionsSuccessResponse
        try:
            instance.actual_instance = GetLeaseArTransactionsSuccessResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GetMitsLeaseArTransactionsSuccessResponse
        try:
            instance.actual_instance = GetMitsLeaseArTransactionsSuccessResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SendLeaseArTransactionReversalsSuccessResponse
        try:
            instance.actual_instance = SendLeaseArTransactionReversalsSuccessResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SendLeaseArTransactionsSuccessResponse
        try:
            instance.actual_instance = SendLeaseArTransactionsSuccessResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into OrgsV1ArtransactionsPost200Response with oneOf schemas: GetArInvoicesSuccessResponse, GetLeaseArTransactionsSuccessResponse, GetMitsLeaseArTransactionsSuccessResponse, SendLeaseArTransactionReversalsSuccessResponse, SendLeaseArTransactionsSuccessResponse. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into OrgsV1ArtransactionsPost200Response with oneOf schemas: GetArInvoicesSuccessResponse, GetLeaseArTransactionsSuccessResponse, GetMitsLeaseArTransactionsSuccessResponse, SendLeaseArTransactionReversalsSuccessResponse, SendLeaseArTransactionsSuccessResponse. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GetArInvoicesSuccessResponse, GetLeaseArTransactionsSuccessResponse, GetMitsLeaseArTransactionsSuccessResponse, SendLeaseArTransactionReversalsSuccessResponse, SendLeaseArTransactionsSuccessResponse]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


