# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.get_pricing_picklists import GetPricingPicklists
from openapi_client.models.get_property_fees import GetPropertyFees
from openapi_client.models.insert_pricing import InsertPricing
from openapi_client.models.insert_pricing_r2 import InsertPricingR2
from openapi_client.models.send_budgeted_rent import SendBudgetedRent
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ORGSV1PRICINGPOSTREQUESTINNER_ONE_OF_SCHEMAS = ["GetPricingPicklists", "GetPropertyFees", "InsertPricing", "InsertPricingR2", "SendBudgetedRent"]

class OrgsV1PricingPostRequestInner(BaseModel):
    """
    OrgsV1PricingPostRequestInner
    """
    # data type: GetPricingPicklists
    oneof_schema_1_validator: Optional[GetPricingPicklists] = None
    # data type: GetPropertyFees
    oneof_schema_2_validator: Optional[GetPropertyFees] = None
    # data type: InsertPricing
    oneof_schema_3_validator: Optional[InsertPricing] = None
    # data type: InsertPricingR2
    oneof_schema_4_validator: Optional[InsertPricingR2] = None
    # data type: SendBudgetedRent
    oneof_schema_5_validator: Optional[SendBudgetedRent] = None
    actual_instance: Optional[Union[GetPricingPicklists, GetPropertyFees, InsertPricing, InsertPricingR2, SendBudgetedRent]] = None
    one_of_schemas: Set[str] = { "GetPricingPicklists", "GetPropertyFees", "InsertPricing", "InsertPricingR2", "SendBudgetedRent" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = OrgsV1PricingPostRequestInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: GetPricingPicklists
        if not isinstance(v, GetPricingPicklists):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetPricingPicklists`")
        else:
            match += 1
        # validate data type: GetPropertyFees
        if not isinstance(v, GetPropertyFees):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetPropertyFees`")
        else:
            match += 1
        # validate data type: InsertPricing
        if not isinstance(v, InsertPricing):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InsertPricing`")
        else:
            match += 1
        # validate data type: InsertPricingR2
        if not isinstance(v, InsertPricingR2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InsertPricingR2`")
        else:
            match += 1
        # validate data type: SendBudgetedRent
        if not isinstance(v, SendBudgetedRent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SendBudgetedRent`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in OrgsV1PricingPostRequestInner with oneOf schemas: GetPricingPicklists, GetPropertyFees, InsertPricing, InsertPricingR2, SendBudgetedRent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in OrgsV1PricingPostRequestInner with oneOf schemas: GetPricingPicklists, GetPropertyFees, InsertPricing, InsertPricingR2, SendBudgetedRent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into GetPricingPicklists
        try:
            instance.actual_instance = GetPricingPicklists.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GetPropertyFees
        try:
            instance.actual_instance = GetPropertyFees.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InsertPricing
        try:
            instance.actual_instance = InsertPricing.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InsertPricingR2
        try:
            instance.actual_instance = InsertPricingR2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SendBudgetedRent
        try:
            instance.actual_instance = SendBudgetedRent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into OrgsV1PricingPostRequestInner with oneOf schemas: GetPricingPicklists, GetPropertyFees, InsertPricing, InsertPricingR2, SendBudgetedRent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into OrgsV1PricingPostRequestInner with oneOf schemas: GetPricingPicklists, GetPropertyFees, InsertPricing, InsertPricingR2, SendBudgetedRent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GetPricingPicklists, GetPropertyFees, InsertPricing, InsertPricingR2, SendBudgetedRent]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


