# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SendApplicationEmployersMethodParams(BaseModel):
    """
    SendApplicationEmployersMethodParams
    """ # noqa: E501
    application_id: StrictInt = Field(description="  This is a required field. This field accepts single value. Required parameter, accepts integer value.", alias="applicationId")
    property_id: StrictInt = Field(description="This is a required field. This field accepts single value. Required parameter, accepts integer value.", alias="propertyId")
    id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Conditionally Required parameter. If provided, it will update the empl oyer record on provided application. otherwise insert the employer record.")
    income_type_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Conditionally Required parameter. If \"id\" is not provided, this parame ter is required.", alias="incomeTypeId")
    customer_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Conditionally Required parameter. If \"id\" is not provided, this parame ter is required.", alias="customerId")
    frequency_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts integer value. If provided should be a val id frequency range which are: 3 [ weekly ], 4 [ Monthly ] and 6 [ Yearly ]", alias="frequencyId")
    position: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value")
    institution_name: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="institutionName")
    institution_phone_number: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accept string value. If provided, should be valid phone number.", alias="institutionPhoneNumber")
    institution_street_line1: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="institutionStreetLine1")
    institution_street_line2: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="institutionStreetLine2")
    institution_street_line3: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="institutionStreetLine3")
    institution_city: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="institutionCity")
    institution_state_code: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="institutionStateCode")
    institution_province: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="institutionProvince")
    institution_postal_code: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="institutionPostalCode")
    institution_country_code: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="institutionCountryCode")
    amount: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Conditionally Required parameter, accepts float value with two decimal points. If Id is not provided, this becomes required.")
    contact_name: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="contactName")
    contact_phone: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accept string value. If provided, should be valid phone number.", alias="contactPhone")
    contact_email: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accepts string value", alias="contactEmail")
    income_effective_date: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accept date in MM/DD/YYYY or YYYY-MM-DD format.", alias="incomeEffectiveDate")
    date_started: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accept date in MM/DD/YYYY or YYYY-MM-DD format.", alias="dateStarted")
    date_ended: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accept date in MM/DD/YYYY or YYYY-MM-DD format. if provided, then dateStarted and dateEnded should be in valid range. da teStarted should be less than dateEnded.", alias="dateEnded")
    is_delete: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Optional parameter, accept either 1 or 0. if provided value as 1 then id is required and the employer record will be removed from applicatio n.", alias="isDelete")
    __properties: ClassVar[List[str]] = ["applicationId", "propertyId", "id", "incomeTypeId", "customerId", "frequencyId", "position", "institutionName", "institutionPhoneNumber", "institutionStreetLine1", "institutionStreetLine2", "institutionStreetLine3", "institutionCity", "institutionStateCode", "institutionProvince", "institutionPostalCode", "institutionCountryCode", "amount", "contactName", "contactPhone", "contactEmail", "incomeEffectiveDate", "dateStarted", "dateEnded", "isDelete"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendApplicationEmployersMethodParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendApplicationEmployersMethodParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "applicationId": obj.get("applicationId"),
            "propertyId": obj.get("propertyId"),
            "id": obj.get("id"),
            "incomeTypeId": obj.get("incomeTypeId"),
            "customerId": obj.get("customerId"),
            "frequencyId": obj.get("frequencyId"),
            "position": obj.get("position"),
            "institutionName": obj.get("institutionName"),
            "institutionPhoneNumber": obj.get("institutionPhoneNumber"),
            "institutionStreetLine1": obj.get("institutionStreetLine1"),
            "institutionStreetLine2": obj.get("institutionStreetLine2"),
            "institutionStreetLine3": obj.get("institutionStreetLine3"),
            "institutionCity": obj.get("institutionCity"),
            "institutionStateCode": obj.get("institutionStateCode"),
            "institutionProvince": obj.get("institutionProvince"),
            "institutionPostalCode": obj.get("institutionPostalCode"),
            "institutionCountryCode": obj.get("institutionCountryCode"),
            "amount": obj.get("amount"),
            "contactName": obj.get("contactName"),
            "contactPhone": obj.get("contactPhone"),
            "contactEmail": obj.get("contactEmail"),
            "incomeEffectiveDate": obj.get("incomeEffectiveDate"),
            "dateStarted": obj.get("dateStarted"),
            "dateEnded": obj.get("dateEnded"),
            "isDelete": obj.get("isDelete")
        })
        return _obj


