# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SendPurchaseOrdersMethodParams(BaseModel):
    """
    SendPurchaseOrdersMethodParams
    """ # noqa: E501
    po_type_id: StrictInt = Field(description="This is a required field. This field accepts single value. Supports purchase order types 4 and 19 (\"Standard\" and \"Standard-Job/ Contract\" respectively).", alias="poTypeId")
    ap_payee_id: StrictInt = Field(description="This is a required field. This field accepts single value. Supports purchase order types 4 and 19 (\"Standard\" and \"Standard-Job/ Contract\" respectively).", alias="apPayeeId")
    ap_payee_location_id: StrictInt = Field(description="This is a required field. This field accepts single value. Child element of apHeader. Location Id of a vendor.", alias="apPayeeLocationId")
    ap_payee_account_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Child element of apHeader. If not passed in the request, the system d efault account will be used.", alias="apPayeeAccountId")
    post_month: date = Field(description="This is a required field. This field accepts single value. Accepts date in MM/YYYY format.", alias="postMonth")
    post_date: date = Field(description="This is a required field. This field accepts single value. Child element of apHeader.", alias="postDate")
    routing_tag_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Child element of apHeader.", alias="routingTagId")
    header_memo: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Child element of apHeader.", alias="headerMemo")
    shipping: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This will specify the shipping amount.")
    discount: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This will specify the discount amount.")
    sales_tax: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This will specify the sales tax of the invoice.", alias="salesTax")
    gl_account_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Child element of apDetail.This is required if po type is standard.", alias="glAccountId")
    ap_code_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This is child element of apDetails. This is required if po type is job costing.", alias="apCodeId")
    job_phase_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This is child element of apDetails. This is required if po type is job costing.", alias="jobPhaseId")
    ap_contract_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This is child element of apDetails.", alias="apContractId")
    property_id: StrictInt = Field(description="This is a required field. This field accepts single value. Child element of apDetail.", alias="propertyId")
    quantity: StrictInt = Field(description="This is a required field. This field accepts single value. Child element of apDetail.")
    rate: StrictInt = Field(description="This is a required field. This field accepts single value. Child element of apDetail.")
    gl_dimension_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Child element of apDetail. Custom Tags.", alias="glDimensionId")
    company_department_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Child element of apDetail.", alias="companyDepartmentId")
    property_unit_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Child element of apDetail.", alias="propertyUnitId")
    property_building_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Child element of apDetail.", alias="propertyBuildingId")
    is_confidential: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Accepts \"0\" or \"1\" Only.", alias="isConfidential")
    is_taxable: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Accepts \"0\" or \"1\" Only.", alias="isTaxable")
    description: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value.")
    __properties: ClassVar[List[str]] = ["poTypeId", "apPayeeId", "apPayeeLocationId", "apPayeeAccountId", "postMonth", "postDate", "routingTagId", "headerMemo", "shipping", "discount", "salesTax", "glAccountId", "apCodeId", "jobPhaseId", "apContractId", "propertyId", "quantity", "rate", "glDimensionId", "companyDepartmentId", "propertyUnitId", "propertyBuildingId", "isConfidential", "isTaxable", "description"]

    @field_validator('is_confidential')
    def is_confidential_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    @field_validator('is_taxable')
    def is_taxable_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendPurchaseOrdersMethodParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendPurchaseOrdersMethodParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "poTypeId": obj.get("poTypeId"),
            "apPayeeId": obj.get("apPayeeId"),
            "apPayeeLocationId": obj.get("apPayeeLocationId"),
            "apPayeeAccountId": obj.get("apPayeeAccountId"),
            "postMonth": obj.get("postMonth"),
            "postDate": obj.get("postDate"),
            "routingTagId": obj.get("routingTagId"),
            "headerMemo": obj.get("headerMemo"),
            "shipping": obj.get("shipping"),
            "discount": obj.get("discount"),
            "salesTax": obj.get("salesTax"),
            "glAccountId": obj.get("glAccountId"),
            "apCodeId": obj.get("apCodeId"),
            "jobPhaseId": obj.get("jobPhaseId"),
            "apContractId": obj.get("apContractId"),
            "propertyId": obj.get("propertyId"),
            "quantity": obj.get("quantity"),
            "rate": obj.get("rate"),
            "glDimensionId": obj.get("glDimensionId"),
            "companyDepartmentId": obj.get("companyDepartmentId"),
            "propertyUnitId": obj.get("propertyUnitId"),
            "propertyBuildingId": obj.get("propertyBuildingId"),
            "isConfidential": obj.get("isConfidential"),
            "isTaxable": obj.get("isTaxable"),
            "description": obj.get("description")
        })
        return _obj


