# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateSpecialGroupMethodParamsSpecialGroupSpecialsInnerRatesInner(BaseModel):
    """
    UpdateSpecialGroupMethodParamsSpecialGroupSpecialsInnerRatesInner
    """ # noqa: E501
    ar_code_id: Optional[StrictStr] = Field(default=None, description="Optional. AR code identifier", alias="arCodeId")
    ar_trigger_id: Optional[StrictStr] = Field(default=None, description="Optional. AR trigger identifier", alias="arTriggerId")
    ar_code_type_id: Optional[StrictStr] = Field(default=None, description="Optional. AR code type identifier", alias="arCodeTypeId")
    customer_relationship_id: Optional[StrictStr] = Field(default=None, description="Optional. Customer relationship identifier", alias="customerRelationshipId")
    lease_term_id: Optional[StrictStr] = Field(default=None, description="Optional. Lease term identifier", alias="leaseTermId")
    lease_term_month: Optional[StrictStr] = Field(default=None, description="Optional. Integer representation of lease term", alias="leaseTermMonth")
    lease_start_window_id: Optional[StrictStr] = Field(default=None, description="Optional. Lease start window identifier", alias="leaseStartWindowId")
    window_start_date: Optional[StrictStr] = Field(default=None, description="Optional. Start date for lease window", alias="windowStartDate")
    window_end_date: Optional[StrictStr] = Field(default=None, description="Optional. End date for lease window", alias="windowEndDate")
    effective_date: Optional[StrictStr] = Field(default=None, description="Optional. Date rate becomes effective", alias="effectiveDate")
    ar_formula_id: Optional[StrictStr] = Field(default=None, description="Optional. AR formula identifier", alias="arFormulaId")
    rate_interval_start: Optional[StrictStr] = Field(default=None, description="Optional. Month when special starts", alias="rateIntervalStart")
    rate_amount: Optional[StrictStr] = Field(default=None, description="Optional. Rate amount", alias="rateAmount")
    rate_increase_increment: Optional[StrictStr] = Field(default=None, description="Optional. Increment for percent base formula", alias="rateIncreaseIncrement")
    ar_formula_reference_id: Optional[StrictStr] = Field(default=None, description="Optional. Additional formula information", alias="arFormulaReferenceId")
    space_configuration_id: Optional[StrictStr] = Field(default=None, description="Optional. Space configuration identifier", alias="spaceConfigurationId")
    show_in_entrata: Optional[StrictStr] = Field(default=None, description="Optional. Display within Entrata", alias="showInEntrata")
    show_on_website: Optional[StrictStr] = Field(default=None, description="Optional. Display on website", alias="showOnWebsite")
    __properties: ClassVar[List[str]] = ["arCodeId", "arTriggerId", "arCodeTypeId", "customerRelationshipId", "leaseTermId", "leaseTermMonth", "leaseStartWindowId", "windowStartDate", "windowEndDate", "effectiveDate", "arFormulaId", "rateIntervalStart", "rateAmount", "rateIncreaseIncrement", "arFormulaReferenceId", "spaceConfigurationId", "showInEntrata", "showOnWebsite"]

    @field_validator('show_in_entrata')
    def show_in_entrata_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['0', '1']):
            raise ValueError("must be one of enum values ('0', '1')")
        return value

    @field_validator('show_on_website')
    def show_on_website_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['0', '1']):
            raise ValueError("must be one of enum values ('0', '1')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateSpecialGroupMethodParamsSpecialGroupSpecialsInnerRatesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateSpecialGroupMethodParamsSpecialGroupSpecialsInnerRatesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "arCodeId": obj.get("arCodeId"),
            "arTriggerId": obj.get("arTriggerId"),
            "arCodeTypeId": obj.get("arCodeTypeId"),
            "customerRelationshipId": obj.get("customerRelationshipId"),
            "leaseTermId": obj.get("leaseTermId"),
            "leaseTermMonth": obj.get("leaseTermMonth"),
            "leaseStartWindowId": obj.get("leaseStartWindowId"),
            "windowStartDate": obj.get("windowStartDate"),
            "windowEndDate": obj.get("windowEndDate"),
            "effectiveDate": obj.get("effectiveDate"),
            "arFormulaId": obj.get("arFormulaId"),
            "rateIntervalStart": obj.get("rateIntervalStart"),
            "rateAmount": obj.get("rateAmount"),
            "rateIncreaseIncrement": obj.get("rateIncreaseIncrement"),
            "arFormulaReferenceId": obj.get("arFormulaReferenceId"),
            "spaceConfigurationId": obj.get("spaceConfigurationId"),
            "showInEntrata": obj.get("showInEntrata"),
            "showOnWebsite": obj.get("showOnWebsite")
        })
        return _obj


