# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_work_orders_success_response import GetWorkOrdersSuccessResponse

class TestGetWorkOrdersSuccessResponse(unittest.TestCase):
    """GetWorkOrdersSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWorkOrdersSuccessResponse:
        """Test GetWorkOrdersSuccessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWorkOrdersSuccessResponse`
        """
        model = GetWorkOrdersSuccessResponse()
        if include_optional:
            return GetWorkOrdersSuccessResponse(
                request_id = '15',
                result = openapi_client.models.get_work_orders_success_response_result.getWorkOrdersSuccessResponse_result(
                    work_orders = openapi_client.models.get_work_orders_success_response_result_work_orders.getWorkOrdersSuccessResponse_result_workOrders(
                        work_order = [
                            openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner(
                                maintenance_request_id = '307132', 
                                property_id = '11111', 
                                building_name = 'B1', 
                                unit_number = '8', 
                                customer_id = '4856298', 
                                name_first = 'Cosin', 
                                name_last = 'Dome', 
                                primary_phone_number = '123456789', 
                                alternate_phone_number = '12121212121', 
                                email_address = 'cosin@dome.com', 
                                created_on = '01/05/2012 05:22:26.184567 MST', 
                                assigned_to = 'jiniaxena', 
                                maintenance_status = 'New', 
                                maintenance_priority = 'NOWrn Never is question', 
                                maintenance_category_name = 'test123', 
                                maintenance_problem = 'Problem With Lights', 
                                maintenance_description = 'Some description', 
                                labors = openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_labors.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_labors(
                                    labor = [
                                        openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_labors_labor_inner.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_labors_labor_inner(
                                            employee_name = 'ABC', 
                                            description = 'sdf', 
                                            labor_type = 'Regular', 
                                            labor_type_id = '1', 
                                            start_date_time = '02/28/2018 01:11:00', 
                                            end_date_time = '02/28/2018 01:15:00', 
                                            total_minutes = '4', 
                                            per_hour_rate = '1.00', 
                                            total_charge = '0.07', )
                                        ], 
                                    sub_total = openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_labors_sub_total.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_labors_subTotal(
                                        total_charge = '10.27', 
                                        total_minutes = 616, ), ), 
                                scheduled_start_date = '01/06/2012 00:00:00 MDT', 
                                scheduled_end_date = '01/09/2012 00:00:00 MDT', 
                                due_date = '02/04/2022 18:34:11 MST', 
                                is_floating = 'false', 
                                permission_to_enter = '0', 
                                pet_info = 'Dogs,Dogs,Dogs,Dogs,Snake,Snake', 
                                alarm_info = '123454', 
                                maintenance_request_from = 'Entrata PaaS', 
                                maintenance_request_by = 'R R1', 
                                is_deleted = '0', 
                                child_work_orders = openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_child_work_orders.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_childWorkOrders(
                                    child_work_order = [
                                        openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_child_work_orders_child_work_order_inner.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_childWorkOrders_childWorkOrder_inner(
                                            maintenance_request_id = '5039921', 
                                            maintenance_status = '1test', 
                                            maintenance_priority = 'JS Testing 1', 
                                            maintenance_problem = '12', 
                                            maintenance_location = '1234', 
                                            completed_on = '03/22/2017 03:27:46 MDT', 
                                            entry_notes = 'This is an entry note', )
                                        ], ), )
                            ], ), )
            )
        else:
            return GetWorkOrdersSuccessResponse(
                request_id = '15',
                result = openapi_client.models.get_work_orders_success_response_result.getWorkOrdersSuccessResponse_result(
                    work_orders = openapi_client.models.get_work_orders_success_response_result_work_orders.getWorkOrdersSuccessResponse_result_workOrders(
                        work_order = [
                            openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner(
                                maintenance_request_id = '307132', 
                                property_id = '11111', 
                                building_name = 'B1', 
                                unit_number = '8', 
                                customer_id = '4856298', 
                                name_first = 'Cosin', 
                                name_last = 'Dome', 
                                primary_phone_number = '123456789', 
                                alternate_phone_number = '12121212121', 
                                email_address = 'cosin@dome.com', 
                                created_on = '01/05/2012 05:22:26.184567 MST', 
                                assigned_to = 'jiniaxena', 
                                maintenance_status = 'New', 
                                maintenance_priority = 'NOWrn Never is question', 
                                maintenance_category_name = 'test123', 
                                maintenance_problem = 'Problem With Lights', 
                                maintenance_description = 'Some description', 
                                labors = openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_labors.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_labors(
                                    labor = [
                                        openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_labors_labor_inner.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_labors_labor_inner(
                                            employee_name = 'ABC', 
                                            description = 'sdf', 
                                            labor_type = 'Regular', 
                                            labor_type_id = '1', 
                                            start_date_time = '02/28/2018 01:11:00', 
                                            end_date_time = '02/28/2018 01:15:00', 
                                            total_minutes = '4', 
                                            per_hour_rate = '1.00', 
                                            total_charge = '0.07', )
                                        ], 
                                    sub_total = openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_labors_sub_total.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_labors_subTotal(
                                        total_charge = '10.27', 
                                        total_minutes = 616, ), ), 
                                scheduled_start_date = '01/06/2012 00:00:00 MDT', 
                                scheduled_end_date = '01/09/2012 00:00:00 MDT', 
                                due_date = '02/04/2022 18:34:11 MST', 
                                is_floating = 'false', 
                                permission_to_enter = '0', 
                                pet_info = 'Dogs,Dogs,Dogs,Dogs,Snake,Snake', 
                                alarm_info = '123454', 
                                maintenance_request_from = 'Entrata PaaS', 
                                maintenance_request_by = 'R R1', 
                                is_deleted = '0', 
                                child_work_orders = openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_child_work_orders.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_childWorkOrders(
                                    child_work_order = [
                                        openapi_client.models.get_work_orders_success_response_result_work_orders_work_order_inner_child_work_orders_child_work_order_inner.getWorkOrdersSuccessResponse_result_workOrders_workOrder_inner_childWorkOrders_childWorkOrder_inner(
                                            maintenance_request_id = '5039921', 
                                            maintenance_status = '1test', 
                                            maintenance_priority = 'JS Testing 1', 
                                            maintenance_problem = '12', 
                                            maintenance_location = '1234', 
                                            completed_on = '03/22/2017 03:27:46 MDT', 
                                            entry_notes = 'This is an entry note', )
                                        ], ), )
                            ], ), ),
        )
        """

    def testGetWorkOrdersSuccessResponse(self):
        """Test GetWorkOrdersSuccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
