# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.orgs_v1_financial_post200_response import OrgsV1FinancialPost200Response

class TestOrgsV1FinancialPost200Response(unittest.TestCase):
    """OrgsV1FinancialPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgsV1FinancialPost200Response:
        """Test OrgsV1FinancialPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrgsV1FinancialPost200Response`
        """
        model = OrgsV1FinancialPost200Response()
        if include_optional:
            return OrgsV1FinancialPost200Response(
                request_id = '15',
                code = '200',
                result = openapi_client.models.update_budgets_success_response_result.updateBudgetsSuccessResponse_result(
                    budgets = openapi_client.models.update_budgets_success_response_result_budgets.updateBudgetsSuccessResponse_result_budgets(
                        budget = [
                            openapi_client.models.update_budgets_success_response_result_budgets_budget_inner.updateBudgetsSuccessResponse_result_budgets_budget_inner(
                                node = '1', 
                                status = 'Success', 
                                message = 'Budget updated successfully.', )
                            ], ), ),
                response = openapi_client.models.get_gl_trees_r2_success_response_response.getGlTrees_r2_SuccessResponse_response(
                    request_id = '15', 
                    code = 200, 
                    result = openapi_client.models.get_gl_trees_r2_success_response_response_result.getGlTrees_r2_SuccessResponse_response_result(
                        gl_trees = openapi_client.models.get_gl_trees_r2_success_response_response_result_gl_trees.getGlTrees_r2_SuccessResponse_response_result_glTrees(
                            gl_tree = [
                                openapi_client.models.get_gl_trees_r2_success_response_response_result_gl_trees_gl_tree_inner.getGlTrees_r2_SuccessResponse_response_result_glTrees_glTree_inner(
                                    id = 12345, 
                                    name = 'Master GL Tree', 
                                    is_master_gl_tree = 1, 
                                    branches = openapi_client.models.get_gl_trees_r2_success_response_response_result_gl_trees_gl_tree_inner_branches.getGlTrees_r2_SuccessResponse_response_result_glTrees_glTree_inner_branches(
                                        branch = [
                                            openapi_client.models.get_gl_trees_r2_success_response_response_result_gl_trees_gl_tree_inner_branches_branch_inner.getGlTrees_r2_SuccessResponse_response_result_glTrees_glTree_inner_branches_branch_inner(
                                                branch_id = '12345', 
                                                group_type = 'Standard Group', 
                                                is_enabled = '1', 
                                                show_group_name = 1, 
                                                group_name = 'Cash', 
                                                show_summary_row = 1, 
                                                description = 'Cash', )
                                            ], ), 
                                    gl_accounts = openapi_client.models.get_gl_trees_r2_success_response_response_result_gl_trees_gl_tree_inner_gl_accounts.getGlTrees_r2_SuccessResponse_response_result_glTrees_glTree_inner_glAccounts(
                                        gl_account = [
                                            openapi_client.models.get_gl_trees_r2_success_response_response_result_gl_trees_gl_tree_inner_gl_accounts_gl_account_inner.getGlTrees_r2_SuccessResponse_response_result_glTrees_glTree_inner_glAccounts_glAccount_inner(
                                                id = '12345', 
                                                branch_id = '12345', 
                                                account_number = '12345-12345', 
                                                account_name = 'Cash in Bank - Operating', 
                                                external_id = '12345', 
                                                gl_group_type = 'Assets', 
                                                group_location = 'Cash', 
                                                description = 'Cash in Bank - Operating', 
                                                status = 'Enabled', 
                                                is_system = 1, )
                                            ], ), )
                                ], ), ), )
            )
        else:
            return OrgsV1FinancialPost200Response(
                request_id = '15',
                code = '200',
                result = openapi_client.models.update_budgets_success_response_result.updateBudgetsSuccessResponse_result(
                    budgets = openapi_client.models.update_budgets_success_response_result_budgets.updateBudgetsSuccessResponse_result_budgets(
                        budget = [
                            openapi_client.models.update_budgets_success_response_result_budgets_budget_inner.updateBudgetsSuccessResponse_result_budgets_budget_inner(
                                node = '1', 
                                status = 'Success', 
                                message = 'Budget updated successfully.', )
                            ], ), ),
        )
        """

    def testOrgsV1FinancialPost200Response(self):
        """Test OrgsV1FinancialPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
