# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from entrata_api_client.models.get_specials_r3_success_response_response import GetSpecialsR3SuccessResponseResponse

class TestGetSpecialsR3SuccessResponseResponse(unittest.TestCase):
    """GetSpecialsR3SuccessResponseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSpecialsR3SuccessResponseResponse:
        """Test GetSpecialsR3SuccessResponseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSpecialsR3SuccessResponseResponse`
        """
        model = GetSpecialsR3SuccessResponseResponse()
        if include_optional:
            return GetSpecialsR3SuccessResponseResponse(
                request_id = '15',
                code = 200,
                result = entrata_api_client.models.get_specials_r3_success_response_response_result.getSpecials_r3_SuccessResponse_response_result(
                    specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials.getSpecials_r3_SuccessResponse_response_result_specials(
                        property_id = 171712, 
                        organization_name = 'Demo Account', 
                        marketing_name = '14 th South Avenue', 
                        legal_name = '14 th South Avenue', 
                        property_specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_property_specials.getSpecials_r3_SuccessResponse_response_result_specials_propertySpecials(
                            special = {
                                'key' : entrata_api_client.models.get_specials_r3_success_response_response_result_specials_property_specials_special_value.getSpecials_r3_SuccessResponse_response_result_specials_propertySpecials_special_value(
                                    id = '12019486', 
                                    name = '90 - 61', 
                                    show_on_website = 1, 
                                    is_active = 1, 
                                    gift_value = '0.00', )
                                }, ), 
                        floorplan_specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_floorplan_specials.getSpecials_r3_SuccessResponse_response_result_specials_floorplanSpecials(
                            special = {
                                'key' : entrata_api_client.models.get_specials_r3_success_response_response_result_specials_floorplan_specials_special_value.getSpecials_r3_SuccessResponse_response_result_specials_floorplanSpecials_special_value(
                                    id = '12033041', 
                                    name = 'Floor special2', 
                                    description = 'Great Deal!!! Great Deal!!! Great Deal!!!', 
                                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    show_on_website = 1, 
                                    is_active = 1, 
                                    gift_value = '200.00', 
                                    floorplans = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_floorplan_specials_special_value_floorplans.getSpecials_r3_SuccessResponse_response_result_specials_floorplanSpecials_special_value_floorplans(
                                        floorplan = [
                                            entrata_api_client.models.get_specials_r3_success_response_response_result_specials_floorplan_specials_special_value_floorplans_floorplan_inner.getSpecials_r3_SuccessResponse_response_result_specials_floorplanSpecials_special_value_floorplans_floorplan_inner(
                                                id = '935877', 
                                                name = 'Catch All Floor Plan', )
                                            ], ), )
                                }, ), 
                        unit_type_specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_type_specials.getSpecials_r3_SuccessResponse_response_result_specials_unitTypeSpecials(
                            special = {
                                'key' : entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_type_specials_special_value.getSpecials_r3_SuccessResponse_response_result_specials_unitTypeSpecials_special_value(
                                    id = '12017831', 
                                    name = 'unit type gift incentive', 
                                    show_on_website = 1, 
                                    is_active = 1, 
                                    gift_value = '300.00', 
                                    unit_types = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_type_specials_special_value_unit_types.getSpecials_r3_SuccessResponse_response_result_specials_unitTypeSpecials_special_value_unitTypes(
                                        unit_type = [
                                            entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_type_specials_special_value_unit_types_unit_type_inner.getSpecials_r3_SuccessResponse_response_result_specials_unitTypeSpecials_special_value_unitTypes_unitType_inner(
                                                id = '577608', 
                                                name = 'Alabaster', )
                                            ], ), )
                                }, ), 
                        unit_space_specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_space_specials.getSpecials_r3_SuccessResponse_response_result_specials_unitSpaceSpecials(
                            special = {
                                'key' : entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_space_specials_special_value.getSpecials_r3_SuccessResponse_response_result_specials_unitSpaceSpecials_special_value(
                                    id = '12034174', 
                                    name = 'Test', 
                                    show_on_website = 1, 
                                    is_active = 1, 
                                    gift_value = '400.00', 
                                    unit_spaces = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_space_specials_special_value_unit_spaces.getSpecials_r3_SuccessResponse_response_result_specials_unitSpaceSpecials_special_value_unitSpaces(
                                        unit_space = [
                                            entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_space_specials_special_value_unit_spaces_unit_space_inner.getSpecials_r3_SuccessResponse_response_result_specials_unitSpaceSpecials_special_value_unitSpaces_unitSpace_inner(
                                                id = '5164266', 
                                                property_unit_id = '4880109', 
                                                name = 'A3', )
                                            ], ), )
                                }, ), ), )
            )
        else:
            return GetSpecialsR3SuccessResponseResponse(
                request_id = '15',
                code = 200,
                result = entrata_api_client.models.get_specials_r3_success_response_response_result.getSpecials_r3_SuccessResponse_response_result(
                    specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials.getSpecials_r3_SuccessResponse_response_result_specials(
                        property_id = 171712, 
                        organization_name = 'Demo Account', 
                        marketing_name = '14 th South Avenue', 
                        legal_name = '14 th South Avenue', 
                        property_specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_property_specials.getSpecials_r3_SuccessResponse_response_result_specials_propertySpecials(
                            special = {
                                'key' : entrata_api_client.models.get_specials_r3_success_response_response_result_specials_property_specials_special_value.getSpecials_r3_SuccessResponse_response_result_specials_propertySpecials_special_value(
                                    id = '12019486', 
                                    name = '90 - 61', 
                                    show_on_website = 1, 
                                    is_active = 1, 
                                    gift_value = '0.00', )
                                }, ), 
                        floorplan_specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_floorplan_specials.getSpecials_r3_SuccessResponse_response_result_specials_floorplanSpecials(
                            special = {
                                'key' : entrata_api_client.models.get_specials_r3_success_response_response_result_specials_floorplan_specials_special_value.getSpecials_r3_SuccessResponse_response_result_specials_floorplanSpecials_special_value(
                                    id = '12033041', 
                                    name = 'Floor special2', 
                                    description = 'Great Deal!!! Great Deal!!! Great Deal!!!', 
                                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    show_on_website = 1, 
                                    is_active = 1, 
                                    gift_value = '200.00', 
                                    floorplans = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_floorplan_specials_special_value_floorplans.getSpecials_r3_SuccessResponse_response_result_specials_floorplanSpecials_special_value_floorplans(
                                        floorplan = [
                                            entrata_api_client.models.get_specials_r3_success_response_response_result_specials_floorplan_specials_special_value_floorplans_floorplan_inner.getSpecials_r3_SuccessResponse_response_result_specials_floorplanSpecials_special_value_floorplans_floorplan_inner(
                                                id = '935877', 
                                                name = 'Catch All Floor Plan', )
                                            ], ), )
                                }, ), 
                        unit_type_specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_type_specials.getSpecials_r3_SuccessResponse_response_result_specials_unitTypeSpecials(
                            special = {
                                'key' : entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_type_specials_special_value.getSpecials_r3_SuccessResponse_response_result_specials_unitTypeSpecials_special_value(
                                    id = '12017831', 
                                    name = 'unit type gift incentive', 
                                    show_on_website = 1, 
                                    is_active = 1, 
                                    gift_value = '300.00', 
                                    unit_types = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_type_specials_special_value_unit_types.getSpecials_r3_SuccessResponse_response_result_specials_unitTypeSpecials_special_value_unitTypes(
                                        unit_type = [
                                            entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_type_specials_special_value_unit_types_unit_type_inner.getSpecials_r3_SuccessResponse_response_result_specials_unitTypeSpecials_special_value_unitTypes_unitType_inner(
                                                id = '577608', 
                                                name = 'Alabaster', )
                                            ], ), )
                                }, ), 
                        unit_space_specials = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_space_specials.getSpecials_r3_SuccessResponse_response_result_specials_unitSpaceSpecials(
                            special = {
                                'key' : entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_space_specials_special_value.getSpecials_r3_SuccessResponse_response_result_specials_unitSpaceSpecials_special_value(
                                    id = '12034174', 
                                    name = 'Test', 
                                    show_on_website = 1, 
                                    is_active = 1, 
                                    gift_value = '400.00', 
                                    unit_spaces = entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_space_specials_special_value_unit_spaces.getSpecials_r3_SuccessResponse_response_result_specials_unitSpaceSpecials_special_value_unitSpaces(
                                        unit_space = [
                                            entrata_api_client.models.get_specials_r3_success_response_response_result_specials_unit_space_specials_special_value_unit_spaces_unit_space_inner.getSpecials_r3_SuccessResponse_response_result_specials_unitSpaceSpecials_special_value_unitSpaces_unitSpace_inner(
                                                id = '5164266', 
                                                property_unit_id = '4880109', 
                                                name = 'A3', )
                                            ], ), )
                                }, ), ), ),
        )
        """

    def testGetSpecialsR3SuccessResponseResponse(self):
        """Test GetSpecialsR3SuccessResponseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
