# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_evicted_leases_success_response_response import GetEvictedLeasesSuccessResponseResponse

class TestGetEvictedLeasesSuccessResponseResponse(unittest.TestCase):
    """GetEvictedLeasesSuccessResponseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEvictedLeasesSuccessResponseResponse:
        """Test GetEvictedLeasesSuccessResponseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEvictedLeasesSuccessResponseResponse`
        """
        model = GetEvictedLeasesSuccessResponseResponse()
        if include_optional:
            return GetEvictedLeasesSuccessResponseResponse(
                request_id = '15',
                code = 200,
                result = openapi_client.models.get_evicted_leases_success_response_response_result.getEvictedLeasesSuccessResponse_response_result(
                    evicted_leases = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases.getEvictedLeasesSuccessResponse_response_result_evictedLeases(
                        summary = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_summary.getEvictedLeasesSuccessResponse_response_result_evictedLeases_summary(
                            generation_time_stamp = '06/28/2017T04:12:23', 
                            source_organization = 'Entrata Inc', 
                            total_properties = '1', 
                            total_lease_files = '37', 
                            total_tenants = '60', 
                            total_open_amount = '688929.50', ), 
                        property_files = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles(
                            property_file = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile(
                                property = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_property.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_property(
                                    id = '123456', 
                                    name = '13th North Parkways Property', 
                                    address = [
                                        openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_property_address_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_property_address_inner(
                                            address_type = 'Primary', 
                                            address = '50 North 100 West', 
                                            city = 'Provo', 
                                            country = 'US', 
                                            state = 'TX', 
                                            postal_code = '89123', )
                                        ], 
                                    phone = [
                                        openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_property_phone_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_property_phone_inner(
                                            phone_type = 'Office', 
                                            phone_number = '8019013023', )
                                        ], ), 
                                lease_files = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles(
                                    lease_file = [
                                        openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner(
                                            lease_id = '5715080', 
                                            eviction_status = 'Evicted', 
                                            move_in_date = '06/02/2014', 
                                            eviction_start_date = '02/26/2015', 
                                            eviction_date = '12/03/2015', 
                                            lease_begin = '06/02/2014', 
                                            lease_end = '09/30/2023', 
                                            monthly_rent_amount = '13.00', 
                                            rent_due_from_date = '06/01/2014', 
                                            rent_due_to_date = '06/01/2017', 
                                            building_name = 'Live', 
                                            unit = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_unit.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_unit(
                                                unit_number = 'MP4-D', 
                                                address = 'MP,PM', 
                                                city = 'PMPM', 
                                                country = 'US', 
                                                state = 'AL', 
                                                postal_code = '52252', ), 
                                            tenants = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_tenants.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_tenants(
                                                tenant = [
                                                    openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_tenants_tenant_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_tenants_tenant_inner(
                                                        customer_id = '6953693', 
                                                        first_name = 'New', 
                                                        last_name = 'Lwersafd', 
                                                        customer_type = 'Primary', 
                                                        phone = [
                                                            openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_tenants_tenant_inner_phone_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_tenants_tenant_inner_phone_inner(
                                                                phone_type = 'cell', 
                                                                phone_number = '2133211231', )
                                                            ], 
                                                        date_of_birth = '12/12/1950', 
                                                        ssn = '111223333', )
                                                    ], ), 
                                            transactions = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_transactions.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_transactions(
                                                transaction = [
                                                    openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_transactions_transaction_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_transactions_transaction_inner(
                                                        transaction_id = '145837339', 
                                                        transaction_date = '06/01/2017', 
                                                        description = 'Application Fee - Monthly Fee Posted from 06/01/2017 to 06/30/2017', 
                                                        transaction_type = 'Charge', 
                                                        transaction_amount = '3.00', 
                                                        open_amount = '3.00', )
                                                    ], ), )
                                        ], ), ), ), ), )
            )
        else:
            return GetEvictedLeasesSuccessResponseResponse(
                request_id = '15',
                code = 200,
                result = openapi_client.models.get_evicted_leases_success_response_response_result.getEvictedLeasesSuccessResponse_response_result(
                    evicted_leases = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases.getEvictedLeasesSuccessResponse_response_result_evictedLeases(
                        summary = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_summary.getEvictedLeasesSuccessResponse_response_result_evictedLeases_summary(
                            generation_time_stamp = '06/28/2017T04:12:23', 
                            source_organization = 'Entrata Inc', 
                            total_properties = '1', 
                            total_lease_files = '37', 
                            total_tenants = '60', 
                            total_open_amount = '688929.50', ), 
                        property_files = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles(
                            property_file = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile(
                                property = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_property.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_property(
                                    id = '123456', 
                                    name = '13th North Parkways Property', 
                                    address = [
                                        openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_property_address_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_property_address_inner(
                                            address_type = 'Primary', 
                                            address = '50 North 100 West', 
                                            city = 'Provo', 
                                            country = 'US', 
                                            state = 'TX', 
                                            postal_code = '89123', )
                                        ], 
                                    phone = [
                                        openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_property_phone_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_property_phone_inner(
                                            phone_type = 'Office', 
                                            phone_number = '8019013023', )
                                        ], ), 
                                lease_files = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles(
                                    lease_file = [
                                        openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner(
                                            lease_id = '5715080', 
                                            eviction_status = 'Evicted', 
                                            move_in_date = '06/02/2014', 
                                            eviction_start_date = '02/26/2015', 
                                            eviction_date = '12/03/2015', 
                                            lease_begin = '06/02/2014', 
                                            lease_end = '09/30/2023', 
                                            monthly_rent_amount = '13.00', 
                                            rent_due_from_date = '06/01/2014', 
                                            rent_due_to_date = '06/01/2017', 
                                            building_name = 'Live', 
                                            unit = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_unit.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_unit(
                                                unit_number = 'MP4-D', 
                                                address = 'MP,PM', 
                                                city = 'PMPM', 
                                                country = 'US', 
                                                state = 'AL', 
                                                postal_code = '52252', ), 
                                            tenants = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_tenants.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_tenants(
                                                tenant = [
                                                    openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_tenants_tenant_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_tenants_tenant_inner(
                                                        customer_id = '6953693', 
                                                        first_name = 'New', 
                                                        last_name = 'Lwersafd', 
                                                        customer_type = 'Primary', 
                                                        phone = [
                                                            openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_tenants_tenant_inner_phone_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_tenants_tenant_inner_phone_inner(
                                                                phone_type = 'cell', 
                                                                phone_number = '2133211231', )
                                                            ], 
                                                        date_of_birth = '12/12/1950', 
                                                        ssn = '111223333', )
                                                    ], ), 
                                            transactions = openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_transactions.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_transactions(
                                                transaction = [
                                                    openapi_client.models.get_evicted_leases_success_response_response_result_evicted_leases_property_files_property_file_lease_files_lease_file_inner_transactions_transaction_inner.getEvictedLeasesSuccessResponse_response_result_evictedLeases_propertyFiles_propertyFile_leaseFiles_leaseFile_inner_transactions_transaction_inner(
                                                        transaction_id = '145837339', 
                                                        transaction_date = '06/01/2017', 
                                                        description = 'Application Fee - Monthly Fee Posted from 06/01/2017 to 06/30/2017', 
                                                        transaction_type = 'Charge', 
                                                        transaction_amount = '3.00', 
                                                        open_amount = '3.00', )
                                                    ], ), )
                                        ], ), ), ), ), ),
        )
        """

    def testGetEvictedLeasesSuccessResponseResponse(self):
        """Test GetEvictedLeasesSuccessResponseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
