# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from entrata_api_client.models.get_specials_r1_success_response import GetSpecialsR1SuccessResponse

class TestGetSpecialsR1SuccessResponse(unittest.TestCase):
    """GetSpecialsR1SuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSpecialsR1SuccessResponse:
        """Test GetSpecialsR1SuccessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSpecialsR1SuccessResponse`
        """
        model = GetSpecialsR1SuccessResponse()
        if include_optional:
            return GetSpecialsR1SuccessResponse(
                response = entrata_api_client.models.get_specials_r1_success_response_response.getSpecials_r1_SuccessResponse_response(
                    request_id = 15, 
                    result = entrata_api_client.models.get_specials_r1_success_response_response_result.getSpecials_r1_SuccessResponse_response_result(
                        physical_property = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty(
                            property = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property(
                                identification = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_identification.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Identification(
                                    id_value = 21442, ), 
                                property_id = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_property_id.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_PropertyID(
                                    identification = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_property_id_identification.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_PropertyID_Identification(
                                        id_value = 21442, 
                                        organization_name = 'DB Xento Systems Pvt. Ltd.', ), 
                                    marketing_name = 'Marketing Name', 
                                    legal_name = 'Legal Name', ), 
                                concession = [
                                    entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_concession_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Concession_inner(
                                        @attributes = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_concession_inner__attributes.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Concession_inner__attributes(
                                            active = 1, ), 
                                        value = '10.00', 
                                        description_header = 'Consession', 
                                        description_body = 'description body', 
                                        description_footer = 'description footer', )
                                    ], 
                                floorplan = [
                                    entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_floorplan_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Floorplan_inner(
                                        identification = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_floorplan_inner_identification.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Floorplan_inner_Identification(
                                            id_value = 127493, ), 
                                        name = 'FP', 
                                        comment = 'FP', 
                                        concession = [
                                            entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_floorplan_inner_concession_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Floorplan_inner_Concession_inner(
                                                @attributes = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_concession_inner__attributes.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Concession_inner__attributes(
                                                    active = 1, ), 
                                                value = '100.00', 
                                                description_header = 'Consession', 
                                                description_body = 'Description', 
                                                description_footer = 'Description', )
                                            ], )
                                    ], 
                                ils_unit = [
                                    entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner(
                                        units = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units(
                                            unit = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units_unit.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units_Unit(
                                                @attributes = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units_unit__attributes.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units_Unit__attributes(
                                                    building_id = 56, 
                                                    floor_plan_id = 127469, ), 
                                                identification = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units_unit_identification.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units_Unit_Identification(
                                                    @attributes = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units_unit_identification__attributes.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units_Unit_Identification__attributes(
                                                        id_rank = 'primary', 
                                                        id_scope_type = 'sender', 
                                                        id_type = 'UnitID', ), 
                                                    id_value = 2261175, ), 
                                                marketing_name = 'unit1', ), ), 
                                        concession = [
                                            entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_concession_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Concession_inner(
                                                @attributes = , 
                                                value = '50.00', 
                                                description_header = 'Test Special', 
                                                description_body = 'description body', 
                                                description_footer = 'description footer', )
                                            ], )
                                    ], ), ), ), )
            )
        else:
            return GetSpecialsR1SuccessResponse(
                response = entrata_api_client.models.get_specials_r1_success_response_response.getSpecials_r1_SuccessResponse_response(
                    request_id = 15, 
                    result = entrata_api_client.models.get_specials_r1_success_response_response_result.getSpecials_r1_SuccessResponse_response_result(
                        physical_property = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty(
                            property = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property(
                                identification = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_identification.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Identification(
                                    id_value = 21442, ), 
                                property_id = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_property_id.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_PropertyID(
                                    identification = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_property_id_identification.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_PropertyID_Identification(
                                        id_value = 21442, 
                                        organization_name = 'DB Xento Systems Pvt. Ltd.', ), 
                                    marketing_name = 'Marketing Name', 
                                    legal_name = 'Legal Name', ), 
                                concession = [
                                    entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_concession_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Concession_inner(
                                        @attributes = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_concession_inner__attributes.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Concession_inner__attributes(
                                            active = 1, ), 
                                        value = '10.00', 
                                        description_header = 'Consession', 
                                        description_body = 'description body', 
                                        description_footer = 'description footer', )
                                    ], 
                                floorplan = [
                                    entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_floorplan_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Floorplan_inner(
                                        identification = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_floorplan_inner_identification.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Floorplan_inner_Identification(
                                            id_value = 127493, ), 
                                        name = 'FP', 
                                        comment = 'FP', 
                                        concession = [
                                            entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_floorplan_inner_concession_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Floorplan_inner_Concession_inner(
                                                @attributes = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_concession_inner__attributes.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_Concession_inner__attributes(
                                                    active = 1, ), 
                                                value = '100.00', 
                                                description_header = 'Consession', 
                                                description_body = 'Description', 
                                                description_footer = 'Description', )
                                            ], )
                                    ], 
                                ils_unit = [
                                    entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner(
                                        units = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units(
                                            unit = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units_unit.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units_Unit(
                                                @attributes = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units_unit__attributes.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units_Unit__attributes(
                                                    building_id = 56, 
                                                    floor_plan_id = 127469, ), 
                                                identification = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units_unit_identification.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units_Unit_Identification(
                                                    @attributes = entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_units_unit_identification__attributes.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Units_Unit_Identification__attributes(
                                                        id_rank = 'primary', 
                                                        id_scope_type = 'sender', 
                                                        id_type = 'UnitID', ), 
                                                    id_value = 2261175, ), 
                                                marketing_name = 'unit1', ), ), 
                                        concession = [
                                            entrata_api_client.models.get_specials_r1_success_response_response_result_physical_property_property_ils_unit_inner_concession_inner.getSpecials_r1_SuccessResponse_response_result_PhysicalProperty_Property_ILS_Unit_inner_Concession_inner(
                                                @attributes = , 
                                                value = '50.00', 
                                                description_header = 'Test Special', 
                                                description_body = 'description body', 
                                                description_footer = 'description footer', )
                                            ], )
                                    ], ), ), ), ),
        )
        """

    def testGetSpecialsR1SuccessResponse(self):
        """Test GetSpecialsR1SuccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
