# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_mits_lease_ar_transactions_success_response_response import GetMitsLeaseArTransactionsSuccessResponseResponse

class TestGetMitsLeaseArTransactionsSuccessResponseResponse(unittest.TestCase):
    """GetMitsLeaseArTransactionsSuccessResponseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMitsLeaseArTransactionsSuccessResponseResponse:
        """Test GetMitsLeaseArTransactionsSuccessResponseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMitsLeaseArTransactionsSuccessResponseResponse`
        """
        model = GetMitsLeaseArTransactionsSuccessResponseResponse()
        if include_optional:
            return GetMitsLeaseArTransactionsSuccessResponseResponse(
                result = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result.getMitsLeaseArTransactionsSuccessResponse_response_result(
                    resident_transactions = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions(
                        property = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_property.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Property(
                            property_id = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_property_property_id.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Property_PropertyID(
                                identification = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_property_property_id_identification.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Property_PropertyID_Identification(
                                    @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_property_property_id_identification__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Property_PropertyID_Identification__attributes(
                                        id_type = 'Property123', ), 
                                    id_value = 12345, ), ), 
                            marketing_name = 'Green Acres', ), 
                        rt_customer = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer(
                            identification = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_identification.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Identification(
                                @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_identification__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Identification__attributes(
                                    id_type = 'LeaseID123', ), 
                                id_value = 98765, ), 
                            customers = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers(
                                customer = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers_customer.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers_Customer(
                                    identification = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers_customer_identification.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers_Customer_Identification(
                                        @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers_customer_identification__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers_Customer_Identification__attributes(
                                            id_type = 'CustID123', ), 
                                        id_value = 56789, ), 
                                    name = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers_customer_name.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers_Customer_Name(
                                        first_name = 'John', 
                                        last_name = 'Doe', ), ), ), ), 
                        unit = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_unit.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Unit(
                            identification = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_unit_identification.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Unit_Identification(
                                @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_unit_identification__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Unit_Identification__attributes(
                                    id_type = 'UnitID123', ), 
                                id_value = 23456, ), 
                            marketing_name = 'Unit A-1', ), 
                        rt_service_transactions = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions(
                            transactions = [
                                openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner(
                                    charge = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_charge.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Charge(
                                        detail = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_charge_detail.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Charge_Detail(
                                            description = 'Late fee', 
                                            transaction_date = '2024-12-19', 
                                            service_to_date = '2024-12-19', 
                                            transaction_id = 123456, 
                                            charge_code = 'LATEFEE', 
                                            supplemental_id = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_charge_detail_supplemental_id.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Charge_Detail_SupplementalID(), 
                                            balance_due = '50.00', 
                                            amount = '50.00', 
                                            reversal_tran_id = 'REV123', ), ), 
                                    payment = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_payment.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Payment(
                                        @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_payment__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Payment__attributes(
                                            payment_type = 'ACH', ), 
                                        detail = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_payment_detail.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Payment_Detail(
                                            description = 'Monthly payment', 
                                            transaction_id = 654321, 
                                            amount_paid = '100.00', 
                                            balance_due = '0.00', ), ), )
                                ], ), ), )
            )
        else:
            return GetMitsLeaseArTransactionsSuccessResponseResponse(
                result = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result.getMitsLeaseArTransactionsSuccessResponse_response_result(
                    resident_transactions = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions(
                        property = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_property.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Property(
                            property_id = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_property_property_id.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Property_PropertyID(
                                identification = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_property_property_id_identification.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Property_PropertyID_Identification(
                                    @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_property_property_id_identification__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Property_PropertyID_Identification__attributes(
                                        id_type = 'Property123', ), 
                                    id_value = 12345, ), ), 
                            marketing_name = 'Green Acres', ), 
                        rt_customer = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer(
                            identification = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_identification.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Identification(
                                @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_identification__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Identification__attributes(
                                    id_type = 'LeaseID123', ), 
                                id_value = 98765, ), 
                            customers = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers(
                                customer = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers_customer.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers_Customer(
                                    identification = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers_customer_identification.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers_Customer_Identification(
                                        @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers_customer_identification__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers_Customer_Identification__attributes(
                                            id_type = 'CustID123', ), 
                                        id_value = 56789, ), 
                                    name = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_customer_customers_customer_name.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RT_Customer_Customers_Customer_Name(
                                        first_name = 'John', 
                                        last_name = 'Doe', ), ), ), ), 
                        unit = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_unit.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Unit(
                            identification = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_unit_identification.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Unit_Identification(
                                @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_unit_identification__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_Unit_Identification__attributes(
                                    id_type = 'UnitID123', ), 
                                id_value = 23456, ), 
                            marketing_name = 'Unit A-1', ), 
                        rt_service_transactions = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions(
                            transactions = [
                                openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner(
                                    charge = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_charge.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Charge(
                                        detail = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_charge_detail.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Charge_Detail(
                                            description = 'Late fee', 
                                            transaction_date = '2024-12-19', 
                                            service_to_date = '2024-12-19', 
                                            transaction_id = 123456, 
                                            charge_code = 'LATEFEE', 
                                            supplemental_id = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_charge_detail_supplemental_id.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Charge_Detail_SupplementalID(), 
                                            balance_due = '50.00', 
                                            amount = '50.00', 
                                            reversal_tran_id = 'REV123', ), ), 
                                    payment = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_payment.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Payment(
                                        @attributes = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_payment__attributes.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Payment__attributes(
                                            payment_type = 'ACH', ), 
                                        detail = openapi_client.models.get_mits_lease_ar_transactions_success_response_response_result_resident_transactions_rt_service_transactions_transactions_inner_payment_detail.getMitsLeaseArTransactionsSuccessResponse_response_result_ResidentTransactions_RTServiceTransactions_Transactions_inner_Payment_Detail(
                                            description = 'Monthly payment', 
                                            transaction_id = 654321, 
                                            amount_paid = '100.00', 
                                            balance_due = '0.00', ), ), )
                                ], ), ), ),
        )
        """

    def testGetMitsLeaseArTransactionsSuccessResponseResponse(self):
        """Test GetMitsLeaseArTransactionsSuccessResponseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
