# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_lease_ar_transactions_success_response import GetLeaseArTransactionsSuccessResponse

class TestGetLeaseArTransactionsSuccessResponse(unittest.TestCase):
    """GetLeaseArTransactionsSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLeaseArTransactionsSuccessResponse:
        """Test GetLeaseArTransactionsSuccessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLeaseArTransactionsSuccessResponse`
        """
        model = GetLeaseArTransactionsSuccessResponse()
        if include_optional:
            return GetLeaseArTransactionsSuccessResponse(
                response = openapi_client.models.get_lease_ar_transactions_success_response_response.getLeaseArTransactionsSuccessResponse_response(
                    request_id = '15', 
                    code = 200, 
                    result = openapi_client.models.get_lease_ar_transactions_success_response_response_result.getLeaseArTransactionsSuccessResponse_response_result(
                        leases = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases.getLeaseArTransactionsSuccessResponse_response_result_leases(
                            lease = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease.getLeaseArTransactionsSuccessResponse_response_result_leases_lease(
                                id = 14803775, 
                                property_id = 172775, 
                                unit_space_id = 5068340, 
                                customers = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers(
                                    customer = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_customer.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_customer(
                                        id = 31094026, 
                                        first_name = 'Alfred', 
                                        last_name = 'Burge', 
                                        is_active_bankruptcy = False, 
                                        bankruptcy_date = '08/22/2025', 
                                        bankruptcy_note = '', ), 
                                    ledgers = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_ledgers.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_ledgers(
                                        ledger = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_ledgers_ledger.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_ledgers_ledger(
                                            id = 11, 
                                            name = 'Resident', 
                                            balance = -924, 
                                            past_due_balance = -924, 
                                            write_off = 0, 
                                            transactions = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_ledgers_ledger_transactions.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_ledgers_ledger_transactions(
                                                transaction = [
                                                    openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_ledgers_ledger_transactions_transaction_inner.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_ledgers_ledger_transactions_transaction_inner(
                                                        id = 11, 
                                                        transaction_type_id = 1, 
                                                        ar_code_id = 1848, 
                                                        ar_code_name = '-Payment', 
                                                        lease_interval_id = 22033341, 
                                                        description = '[]', 
                                                        transaction_date = '08/28/2020', 
                                                        post_date = '08/28/2020', 
                                                        post_month = '09/01/2020', 
                                                        is_temporary = True, 
                                                        balance_due = -12, 
                                                        amount = -12, 
                                                        amount_paid = 0, 
                                                        scheduled_charge_id = 4202932, 
                                                        credit_ar_transaction_ids = '340292930,340302015', 
                                                        ar_payment_id = 123456789, )
                                                    ], ), ), ), ), ), ), ), )
            )
        else:
            return GetLeaseArTransactionsSuccessResponse(
                response = openapi_client.models.get_lease_ar_transactions_success_response_response.getLeaseArTransactionsSuccessResponse_response(
                    request_id = '15', 
                    code = 200, 
                    result = openapi_client.models.get_lease_ar_transactions_success_response_response_result.getLeaseArTransactionsSuccessResponse_response_result(
                        leases = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases.getLeaseArTransactionsSuccessResponse_response_result_leases(
                            lease = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease.getLeaseArTransactionsSuccessResponse_response_result_leases_lease(
                                id = 14803775, 
                                property_id = 172775, 
                                unit_space_id = 5068340, 
                                customers = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers(
                                    customer = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_customer.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_customer(
                                        id = 31094026, 
                                        first_name = 'Alfred', 
                                        last_name = 'Burge', 
                                        is_active_bankruptcy = False, 
                                        bankruptcy_date = '08/22/2025', 
                                        bankruptcy_note = '', ), 
                                    ledgers = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_ledgers.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_ledgers(
                                        ledger = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_ledgers_ledger.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_ledgers_ledger(
                                            id = 11, 
                                            name = 'Resident', 
                                            balance = -924, 
                                            past_due_balance = -924, 
                                            write_off = 0, 
                                            transactions = openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_ledgers_ledger_transactions.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_ledgers_ledger_transactions(
                                                transaction = [
                                                    openapi_client.models.get_lease_ar_transactions_success_response_response_result_leases_lease_customers_ledgers_ledger_transactions_transaction_inner.getLeaseArTransactionsSuccessResponse_response_result_leases_lease_customers_ledgers_ledger_transactions_transaction_inner(
                                                        id = 11, 
                                                        transaction_type_id = 1, 
                                                        ar_code_id = 1848, 
                                                        ar_code_name = '-Payment', 
                                                        lease_interval_id = 22033341, 
                                                        description = '[]', 
                                                        transaction_date = '08/28/2020', 
                                                        post_date = '08/28/2020', 
                                                        post_month = '09/01/2020', 
                                                        is_temporary = True, 
                                                        balance_due = -12, 
                                                        amount = -12, 
                                                        amount_paid = 0, 
                                                        scheduled_charge_id = 4202932, 
                                                        credit_ar_transaction_ids = '340292930,340302015', 
                                                        ar_payment_id = 123456789, )
                                                    ], ), ), ), ), ), ), ), ),
        )
        """

    def testGetLeaseArTransactionsSuccessResponse(self):
        """Test GetLeaseArTransactionsSuccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
