# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MoveOutLeaseMethodParams(BaseModel):
    """
    MoveOutLeaseMethodParams
    """ # noqa: E501
    property_id: StrictInt = Field(description="This is a required field. This field accepts single value. Property id", alias="propertyId")
    lease_id: StrictInt = Field(description="This is a required field. This field accepts single value. leaseId", alias="leaseId")
    move_out_type_id: StrictInt = Field(description="This is a required field. This field accepts single value. moveOutTypeId", alias="moveOutTypeId")
    move_out_reason_id: StrictInt = Field(description="This is a required field. This field accepts single value. moveOutReasonId", alias="moveOutReasonId")
    notice_date: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value. noticeDate", alias="noticeDate")
    move_out_date: date = Field(description="This is a required field. This field accepts single value. moveOutDate", alias="moveOutDate")
    unit_available_on_date: date = Field(description="This is a required field. This field accepts single value. unitAvailableOnDate", alias="unitAvailableOnDate")
    end_continuing_scheduled_charges: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. endContinuingScheduledCharges", alias="endContinuingScheduledCharges")
    post_accelerated_rent: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. postAcceleratedRent", alias="postAcceleratedRent")
    refund_method_id: Optional[StrictInt] = Field(default=None, description="  This is an optional field. This field accepts single value. refundMethodId", alias="refundMethodId")
    make_ready_end_date: Optional[date] = Field(default=None, description="This is an optional field. This field accepts single value. According to Property Preference \"Require Make Ready Work Order on Mov e-out,...\" the makeReadyEndDate is conditional mandatory.", alias="makeReadyEndDate")
    street_line1: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Forwarding Address street_Line1", alias="streetLine1")
    street_line2: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Forwarding Address street_Line2", alias="streetLine2")
    street_line3: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Forwarding Address street_Line3", alias="streetLine3")
    city: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Forwarding address`s city")
    state_code: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. Forwarding Address`s stateCode", alias="stateCode")
    postal_code: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. Forwarding Address`s Postal Code", alias="postalCode")
    __properties: ClassVar[List[str]] = ["propertyId", "leaseId", "moveOutTypeId", "moveOutReasonId", "noticeDate", "moveOutDate", "unitAvailableOnDate", "endContinuingScheduledCharges", "postAcceleratedRent", "refundMethodId", "makeReadyEndDate", "streetLine1", "streetLine2", "streetLine3", "city", "stateCode", "postalCode"]

    @field_validator('end_continuing_scheduled_charges')
    def end_continuing_scheduled_charges_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    @field_validator('post_accelerated_rent')
    def post_accelerated_rent_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MoveOutLeaseMethodParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MoveOutLeaseMethodParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "propertyId": obj.get("propertyId"),
            "leaseId": obj.get("leaseId"),
            "moveOutTypeId": obj.get("moveOutTypeId"),
            "moveOutReasonId": obj.get("moveOutReasonId"),
            "noticeDate": obj.get("noticeDate"),
            "moveOutDate": obj.get("moveOutDate"),
            "unitAvailableOnDate": obj.get("unitAvailableOnDate"),
            "endContinuingScheduledCharges": obj.get("endContinuingScheduledCharges"),
            "postAcceleratedRent": obj.get("postAcceleratedRent"),
            "refundMethodId": obj.get("refundMethodId"),
            "makeReadyEndDate": obj.get("makeReadyEndDate"),
            "streetLine1": obj.get("streetLine1"),
            "streetLine2": obj.get("streetLine2"),
            "streetLine3": obj.get("streetLine3"),
            "city": obj.get("city"),
            "stateCode": obj.get("stateCode"),
            "postalCode": obj.get("postalCode")
        })
        return _obj


