# coding: utf-8

"""
    Entrata APIs

    The Entrata API retrieves property data for marketing, leasing, residents, and more. Our API is organized around RPC protocols, and authenticates users by API key. Additionally, users can only access the API when companies explicitly provide access per user.  ### Time Zones Please note that unless stated otherwise, all dates and times used in the API are assumed to be in Mountain Time (MST or MDT).  ### Languages The `Accept-Language` request header parameter can be used to request that the values returned in the response be translated into the language and locale that is desired, provided that the language is active and enabled for the client. Possible values are: - English: en-US, en-CA, en-GB, en-IE - Spanish: es-MX, es-PE, es-US, es-ES, es-CL   - Hindi: hi-IN - Chinese: zh-CN - French: fr-FR  ### Throttling To maintain a reliable API, Entrata implements rate limits, which restrict the number of API calls you can make within a minute, an hour, and a day. Each API service has its own set of limits, which are detailed in its response headers. Before building your integration, please familiarize yourself with these limits to avoid issues as you scale your usage with more properties or larger clients. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class VoidApPaymentsMethodParams(BaseModel):
    """
    VoidApPaymentsMethodParams
    """ # noqa: E501
    payment_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This is a conditional mandatory node. If the value for paymentNumber, paymentBankAccountId, paymenttypeId, paymentAmount are not provided.", alias="paymentId")
    payment_number: Optional[StrictStr] = Field(default=None, description="This is an optional field. This field accepts single value. This is a conditional mandatory node. If the value for paymentId is no t provided then this node is required.", alias="paymentNumber")
    payment_bank_account_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This is a conditional mandatory node. If the value of paymentId is not provided then this node is required.", alias="paymentBankAccountId")
    payment_type_id: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This is a conditional mandatory node. If the value of paymentId is not provided then this node is required.", alias="paymentTypeId")
    payment_amount: Optional[StrictInt] = Field(default=None, description="This is an optional field. This field accepts single value. This is a conditional mandatory node. If the value of paymentId is not provided then this node is required.", alias="paymentAmount")
    void_date: date = Field(description="This is a required field. This field accepts single value. Supported date format: MM/DD/YYY, M/D/YYYY, YYYY-MM-DD.", alias="voidDate")
    post_month: date = Field(description="This is a required field. This field accepts single value. Supported Format: MM/YYYY", alias="postMonth")
    note: StrictStr = Field(description="This is a required field. This field accepts single value. Memo for the payment")
    __properties: ClassVar[List[str]] = ["paymentId", "paymentNumber", "paymentBankAccountId", "paymentTypeId", "paymentAmount", "voidDate", "postMonth", "note"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VoidApPaymentsMethodParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VoidApPaymentsMethodParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "paymentId": obj.get("paymentId"),
            "paymentNumber": obj.get("paymentNumber"),
            "paymentBankAccountId": obj.get("paymentBankAccountId"),
            "paymentTypeId": obj.get("paymentTypeId"),
            "paymentAmount": obj.get("paymentAmount"),
            "voidDate": obj.get("voidDate"),
            "postMonth": obj.get("postMonth"),
            "note": obj.get("note")
        })
        return _obj


